### DISCUSSION TITLE
A CSS snippet to fix compatibility of SNW plugin under Mininal theme with image grid CSS snippet.

### DISCUSSION THREAD

**Discussion by KuiyueRO** [TfTHacker/obsidian42-strange-new-worlds#114] [Ideas]
```CSS
.snw-reference {
    text-align: center;
    max-height: 20px;
}

.img-grid .markdown-preview-section>div:has(.image-embed)>p {
    grid-template-columns: repeat(auto-fit,minmax(0, max-content));
}

.img-grid .markdown-preview-section>div:has(.image-embed)>p:has([alt*="banner"]) {
    display: inherit;
}
```
### before

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/63145205/653b1503-ba67-4f89-9123-5fef61d9b355)

### now

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/63145205/82cc2d54-e253-4212-90a6-c7296adb25f9)
