### DISCUSSION TITLE
Edting Toolbar plugin compatiblity

### DISCUSSION THREAD

**Discussion by TfTHacker** [TfTHacker/obsidian42-strange-new-worlds#156] [Show and tell]
SNW has CSS for handling the Editing Toolbar plugin if the toolbar is anchored to the top of the document. However, this may not work with some themes. In that case, you can use this CSS Snippet to tweak the position of the SNW Reference Counter at the top of the document.

```css
.view-content:has(.top.cMenuToolbarDefaultAesthetic),
.view-content:has(.top.cMenuToolbarTinyAesthetic) {
  .snw-header-count-wrapper {
    top: 80px;
  }
}

.view-content:has(.top.cMenuToolbarGlassAesthetic) {
  .snw-header-count-wrapper {
    top: 70px;
  }
}
```
