### ISSUE TITLE
[Feature request] Show SNW indicators in PDF export

### ISSUE THREAD

**Issue by koenbunders** [TfTHacker/obsidian42-strange-new-worlds#108]
I'd love to be able to toggle between Show SNW indicators in PDF export , or not.

Thanks!

**Comment by scorchio** [comment]
I had a similar issue - normally in PDF exports, I don't want to see the SNW indicators. A workaround is adding a CSS snippet in Obsidian's Options → Appearance, with a CSS override like this:

```css
@media print {
    .snw-reference {
        display: none;
    }
}
```

(PDF export uses the print style sheets as expected, it seems.)
