### ISSUE TITLE
Location issues with plugins

### ISSUE THREAD

**Issue by zsygmmydnh** [TfTHacker/obsidian42-strange-new-worlds#155]
![PixPin_2024-12-04_14-15-18](https://github.com/user-attachments/assets/6aa847b2-dea1-4180-9b33-f84f3847bc46)
The position of the plug-in conflicts slightly with the position of another plug-in, can you let the plug-in move the position a little? I think moving a little more to the right would solve this problem

**Comment by TfTHacker** [comment]
Thank you for writing. The general solution is to use a little CSS, as you can modify the way the reference counter appears. Are you familiar with CSS to do this?

**Comment by zsygmmydnh** [comment]
Sorry, I'm not very familiar with CSS

**Comment by TfTHacker** [comment]
Which plugin is this conflicting with?

**Comment by zsygmmydnh** [comment]
editing toolbar

**Comment by TfTHacker** [comment]
With the last update I added CSS to handle an exception for this plugin. However, it may not match your theme. If that is the case you will need to add a CSS snippet to your vault and tweak the settings.

```css
.view-content:has(.top.cMenuToolbarDefaultAesthetic),
.view-content:has(.top.cMenuToolbarTinyAesthetic) {
  .snw-header-count-wrapper {
    top: 80px;
  }
}

.view-content:has(.top.cMenuToolbarGlassAesthetic) {
  .snw-header-count-wrapper {
    top: 70px;
  }
}
```
